// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4PhH3-v0st7ZPMB-Vba58z_2sRN7YdRc',
    appId: '1:254871228994:web:e91fc76e570db4be4313db',
    messagingSenderId: '254871228994',
    projectId: 'e-grave',
    authDomain: 'e-grave.firebaseapp.com',
    storageBucket: 'e-grave.appspot.com',
    measurementId: 'G-8W2WHNWS45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7MgBZ_lFpCeju0Sgfs8P-9tta-D8gf0U',
    appId: '1:254871228994:android:ab318b88eeacd26a4313db',
    messagingSenderId: '254871228994',
    projectId: 'e-grave',
    storageBucket: 'e-grave.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDZwsPU4qdhQtGY3_zSHlWuE48QQNetGY',
    appId: '1:254871228994:ios:2b1029b1217432d84313db',
    messagingSenderId: '254871228994',
    projectId: 'e-grave',
    storageBucket: 'e-grave.appspot.com',
    iosClientId: '254871228994-ibj8ikjiu8fdu9mb04rh8649ur3u4g3o.apps.googleusercontent.com',
    iosBundleId: 'com.abewea.graveapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDZwsPU4qdhQtGY3_zSHlWuE48QQNetGY',
    appId: '1:254871228994:ios:b9441e266aa60e224313db',
    messagingSenderId: '254871228994',
    projectId: 'e-grave',
    storageBucket: 'e-grave.appspot.com',
    iosClientId: '254871228994-07sn3qsr4c23ln3fvpbpjqm391g5e33t.apps.googleusercontent.com',
    iosBundleId: 'com.example.graveApps',
  );
}
